### ISSUE TITLE
Can't checkout repo because filename

### ISSUE THREAD

**Issue by lunarcloud** [apancik/public-domain-icons#1]
"symbol heart heart love ❤ <3 like save.svg" Causes it to fail to clone on Windows.

**Comment by phx-veronica** [comment]
I am having the same issue. Emojis usually work in filenames, but the console redirection character `<` is a very bad idea even on UNIX (it won't fail immediately but it could break shell scripts).

Git output on Windows:
```
"C:\Program Files\Git\bin\git.exe" checkout -B "master" "origin/master"
error: invalid path 'dist/symbol heart heart love ❤ <3 like save.svg'
Done
```
